---
apiVersion: v1
kind: Secret
metadata:
  name: rhdh-secrets
  namespace: demo-project
  labels:
    app.kubernetes.io/managed-by: argocd
type: Opaque
stringData:
  BACKEND_SECRET: N4KQcvTEIi6lAMGB5S0vHvBZdeAh789+J
  K8S_SA_TOKEN: eyJhbGciOiJSUzI1NiIsImtpZCI6IjhCWDhydXIyTDNzd1N2X0NuZ2pZV1hXVDNPWlBPMlpEVjdDVzZXQXdhWGcifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJkZW1vLXByb2plY3QiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlY3JldC5uYW1lIjoicmhkaC1rOHMtc2EtdG9rZW4iLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoicmhkaC1rOHMtc2EiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC51aWQiOiIwNzFjMTYwYS0wODEyLTRkNGMtODEyMy1hYTBmZDZjM2QzMjIiLCJzdWIiOiJzeXN0ZW06c2VydmljZWFjY291bnQ6ZGVtby1wcm9qZWN0OnJoZGgtazhzLXNhIn0.o-CmgdJgOoVCZPrfSmWb5DcV-TnrC5S9hlUmX8I7e44MKdcbhcVc08tYB4PIoLGYSDzy8fgAbqJmQAiI7sc6LyTa64QZw6hhOtzLxVEqOQeOecw2DIabrUGHeqMjXLOZRJ8txKh1pshsyFHObHrXJbZaDU_vzAlPVOMfXVwgCTZrTmQP8QyYnRE0RcA7UKZHBzlYa3nLhaD_AoCnBAOQMsApqVplmfWaXw6urCZRWBuwf1ETw0EZUV6i9gMiIxzzXGq6dNrWJ2jIbdh83Z0AMFx7jK_LpcJBev4_5SOeHH3DJ54esbNlR_307D7L0Veqi_rb4ko6dNC8PeKOkTzqoXdnnPeWnXBRt1Kdn0dyOsC53YBl5ikO6EcNcU3m_nBgr_xJyMe6-mvtCQouW2LnMia3mRmYCx6mWqTMZuYk9LM404qXbEQ5soudCH_lR7Os8CD7Hzh_fAP-7Q4UuNhQ3Fg59GfEvuduSA37f4FRwjz1CdY4RqIxntaBXDg8Z_ThWqfjT78wN1q6PwLoqwtQterKaukW9PbAMecaTxAJ3Iyp2OfW-kLdeFc1NHt1z9ixUJT1fSzL4UgFKSeNN07CnfyvhqmFFDneF4yGIg-uUYzB1w4NksyI1Mxm17tIT0glylhKwTMz9ZRuXjqwCk3z6sASQGMITCIPvdvWWV3gST8
